# Generated by Django 2.0.13 on 2019-06-08 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=0, max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('order', models.CharField(max_length=50)),
            ],
        ),
    ]
